# put things common between dev and prod
version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=emoshimo
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
