version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js # overwrite CMD in Dockerfile

# any time you make a change in image you need to build it again in production environment
